#Attribution:  tbd

services:
  web:
    image: louislam/uptime-kuma:1.23.11
    depends_on:
      - tailscale
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      - UPTIME_KUMA_PORT=80
    volumes:
      - data:/app/data

  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.74.1
    restart: unless-stopped
    environment:
      - TS_AUTHKEY={{ secrets.tailscale_authkey }}?ephemeral=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:container,tag:internal-app
      - TS_SERVE_CONFIG=/config/ts-serve.json
      - TS_HOSTNAME=uptime
    volumes:
      - "./tailscale_var_lib:/var/lib"
      - "./config:/config"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
